### ISSUE TITLE
Update installation instructions for Ubuntu

### ISSUE THREAD

**Issue by espectalll** [flatpak/flatpak.github.io#260]
Ubuntu 18.04 LTS has just been released, and it comes with Flatpak on its repos (see https://packages.ubuntu.com/artful/flatpak and https://packages.ubuntu.com/artful/gnome-software-plugin-flatpak)

Correct installation steps would be:

1. `sudo apt update`
2. `sudo apt install flatpak`
3. `sudo apt install gnome-software-plugin-flatpak`*
4. Restart

*couldn't steps 1, 2 and 3 be done on a single command?

**Comment by allanday** [comment]
What do you think, @alexlarsson ?

**Comment by ahayzen** [comment]
Steps 2 and 3 could be combined into one `sudo apt install flatpak gnome-software-plugin-flatpak`, however this assumes that people are running on GNOME (or using gnome-software) :-) 

The PPA is building for bionic [0] and works fine for me with `$ sudo add-apt-repository ppa:alexlarsson/flatpak` (on new versions of apt it seems to auto run `sudo apt update` but i'd recommend keeping it for older releases - as the launchpad page suggests).

Flatpak is in the Ubuntu archive, and I'm trying to keep it up to date, however due to the fast pace of development it was previously recommended to keep the PPA until, for example, version 1.0 is released and makes it in the archive.

0 - https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak?field.series_filter=bionic

**Comment by allanday** [comment]
I just tried the PPA on Bionic and it worked fine.

As @ahayzen mentioned, we're recommending that Ubuntu users use the PPA for the time being. Once 1.0 is out we can think about recommending the version from the standard Ubuntu repos.

**Comment by cassidyjames** [comment]
Gotcha, I must have tried it a couple of weeks ago leading up to the release before the packages were being built.

**Comment by chalan51** [comment]
Uups, I cannot install flatpak on ubuntu 14.04, after 
1- sudo add-apt-repository ppa:alexlarsson/flatpak
2- sudo apt update
3- sudo apt install flatpak
I receive the error 
E: can not be able to locate flatpak package 
   (E: No se ha podido localizar el paquete flatpak)
Please direct me to some support regarding this issue
Thanks

**Comment by ahayzen** [comment]
@chalan51 Unfortunately the PPA is not built for trusty (Ubuntu 14.04), this could be due to many reasons - such as packages or kernel in the archive being too old etc.

Furthermore 14.04 is only supported for around 8-9 months, so personally I don't believe there is much value in trying to package to such an old system which is about to become unsupported. (this is just my opinion, maybe others have different views and have the time to do such work).

I would advise you to upgrade to either 16.04 or 18.04 when and if possible.

**Comment by chalan51** [comment]
Uups.
Since some time ago i've been trying to get authorization to upgrade the device, but i have not got it.
Thanks anyway.
