### ISSUE TITLE
Doesn't work:  sudo apt install gnome-software-plugin-flatpak

### ISSUE THREAD

**Issue by gitclem** [flatpak/flatpak.github.io#285]
On page:
https://flatpak.org/setup/Ubuntu/

It says:

> Install the Software Flatpak plugin
> The Flatpak plugin for the Software app makes it possible to install apps without needing the command line. To install, run:

but it doesn't work:

    sudo apt install gnome-software-plugin-flatpak
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package gnome-software-plugin-flatpak

I'm on Ubuntu 16.04

**Comment by ahayzen** [comment]
`gnome-software-plugin-flatpak` is only provided from artful (Ubuntu 17.10) onwards see (1)  And it is not provided by the PPA (probably because it would a lot of effort to backport the plugin to gnome-software 3.20).

1 - https://packages.ubuntu.com/search?keywords=gnome-software-plugin-flatpak&searchon=names&suite=all&section=all

**Comment by ahayzen** [comment]
(Note that this doesn't mean you cannot use flatpak on Ubuntu 16.04, it just means that you have to use the flatpak command line interface rather than gnome-software GUI)

**Comment by mwleeds** [comment]
Last I checked last year on a newer release of Ubuntu this does work
