### ISSUE TITLE
Add KDE Neon to Quick Setup Page/List of Compatible Distros 

### ISSUE THREAD

**Issue by jhaus33** [flatpak/flatpak.github.io#369]
I'm a Linux novice, so I'm probably missing something here, but why is Kubuntu listed as a compatible distro and KDE Neon is not?

You can add the Flatpak repository in the KDE Neon Discover software center. Seems compatible to me.

Regardless of the option to add the Flatpak repository via the Discover software center, I'm assuming you can  just copy terminal command info from the Kubuntu Quick Start page.

Thank you.

**Comment by haggen88** [comment]
The new KDE neon [5.19](https://kde.org/announcements/plasma-5.19.0) already has Flatpak installed. 

![Neon 5 19](https://user-images.githubusercontent.com/68134588/88734248-83991980-d127-11ea-80ad-cb5d65de331f.png)


To activate Flatpak's built-in support just go to Discover> Settings> Flatpak> Add Flathub and  mark Flatpak as Default.
In previous versions you must add the URI of the repository in Add Source:  https://flathub.org/repo/flathub.flatpakrepo

https://community.kde.org/Guidelines_and_HOWTOs/Flatpak

KDE neon logo:
[KDE neon 128px.svg.zip](https://github.com/flatpak/flatpak.github.io/files/5031478/KDE.Neon.128px.svg.zip)

**Comment by haggen88** [comment]
**update**

KDE neon according to its developers is not a [distro](https://neon.kde.org/faq) in the traditional aspect, it is rather a platform that is based on the latest Ubuntu LTS to test the latest KDE Plasma in continuous updates [it is something like a "Rolling Plasma"].

Since at least Discover 5.12 includes Flatpak installation support, but those KDE neon releases that used that version of Discover were based on Ubuntu LTS versions that have now ended their support:

KDE neon 17> Xenial-based / Plasma: 5.11.4 / Discover 5.11.4 - without Flatpak / EOL of the LTS base
KDE neon 18> Xenial-based / Plasma: 5.13.5 / Discover 5.13.5 - without Flatpak / EOL of the LTS base
KDE neon 19> Bionic-based / Plasma: 5.17.4 / Discover 5.17.4 - with Flatpak 1.0.9 and "plasma-discover-backend-flatpak"
KDE neon 20> Focal-based / Plasma: 5.20.4 / Discover 5.20.4 - with Flatpak 1.6.5 and "plasma-discover-backend-flatpak"
KDE neon 21> Focal-based / Plasma: 5.23.2 / Discover 5.23.2 - with Flatpak 1.11.3 and "plasma-discover-backend-flatpak"

Flatpak is installed by default since KDE neon 19.  It is not necessary to mark Flatpak as default for the apps to appear, that only limits the search for apps to the Flathub repository.

As a preventive measure, it only remains to confirm that the support is activated. Therefore the instructions in Quick Setup should be something like:

Enable Flatpak through the Software Manager</h2>
Flatpak support is built in by default from KDE neon 19 and later. To activate the Flathub repository in Discover, just follow the instructions below:
-Open Discover and click on Settings (lower left corner).
-Check that in the Flatpak section the box is checked.

Note: with this Flathub app search will be integrated in Discover, if you want to limit the app search to Flathub you can mark Flatpak as default by clicking on the star.
