### ISSUE TITLE
Quick Setup: add flathub repo with `--user` flag by default

### ISSUE THREAD

**Issue by soredake** [flatpak/flatpak.github.io#560]
I think it's better to add flathub repo as `user` repo by default, to avoid potential pollution of /var/tmp (https://github.com/flatpak/flatpak/issues/528 and https://github.com/endlessm/systemd/commit/6bdb355a9e515b7b84ac1f37747603d4db4267c7) on distro's that don't clean up this path (opensuse for example) and to avoid any use of polkit (no entering password's anymore on distro's that require it when working with flatpak). Another reasons for using `user` over `system` can be found here https://bugs.kde.org/show_bug.cgi?id=441428#c6

**Comment by o-alquimista** [comment]
Transferred from [this issue](https://github.com/flathub/documentation/issues/116) over at Flathub:

From https://docs.flathub.org/docs/for-users/user-vs-system-install/
> Per-user installations are recommended for most users, unless they have a specific reason to use system-wide installations.

If it's recommended, then why don't we mention that in the [Setup Flatpak](https://flathub.org/setup/Debian) pages?

From the Debian page:

![Captura de tela_2023-11-12_14-48-55](https://github.com/flathub/documentation/assets/25424263/349553da-927a-4d8e-bebb-e0a908faffb4)

It could be just a link for more information. Otherwise most users will be installing system-wide.

**Comment by AsciiWolf** [comment]
System-wide installation is the default option for now.
