### ISSUE TITLE
No explanation how to install runtimes

### ISSUE THREAD

**Issue by csoriano1618** [flatpak/flatpak.github.io#85]
Basically I had to figure it out based on the descriptions and the man page of the command line utility.
http://flatpak.org/runtimes.html should have the command line installation instructions like http://flatpak.org/apps.html has.

**Comment by allanday** [comment]
Runtimes should be automatically installed when installing an application.

To me, this means that the runtimes page is primarily for developers deciding which runtime to build against. As such, I think it's better to explicitly link to the developer docs, rather than have instructions in multiple places.

I've made a small change here that should help:

https://github.com/flatpak/flatpak.github.io/commit/2668b0a52a434913ab9b114a0d7a2ad7b1af7713

**Comment by allanday** [comment]
Work is planned to improve the docs and should take care of this issue. I don't think we need this particular report in order to make sure that it happens.
